apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.serviceAccount.clientId | quote }}
    azure.workload.identity/tenant-id: {{ .Values.azure.tenantId | quote }}
