server:
  port: 8083

spring:
  application:
    name: card-service
  datasource:
    url: jdbc:postgresql://localhost:5433/card_db
    username: novabank
    password: novabank
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
